export const timeZones = [
    { name: "International Date Line West", value: "GMT -12:00" },
    { name: "Samoa Standard Time", value: "GMT -11:00" },
    { name: "Hawaii-Aleutian Standard Time", value: "GMT -10:00" },
    { name: "Alaska Standard Time", value: "GMT -09:00" },
    { name: "Pacific Standard Time (USA, Canada)", value: "GMT -08:00" },
    { name: "Mountain Standard Time (USA, Canada)", value: "GMT -07:00" },
    { name: "Central Standard Time (USA, Canada, Mexico)", value: "GMT -06:00" },
    { name: "Eastern Standard Time (USA, Canada)", value: "GMT -05:00" },
    { name: "Atlantic Standard Time (Canada)", value: "GMT -04:00" },
    { name: "Bolivia Time", value: "GMT -04:00" },
    { name: "Argentina Time", value: "GMT -03:00" },
    { name: "Brazil Time (East)", value: "GMT -03:00" },
    { name: "Uruguay Time", value: "GMT -03:00" },
    { name: "South Georgia Standard Time", value: "GMT -02:00" },
    { name: "Azores Time", value: "GMT -01:00" },
    { name: "Greenwich Mean Time", value: "GMT +00:00" },
    { name: "Western European Time", value: "GMT +00:00" },
    { name: "Central European Time", value: "GMT +01:00" },
    { name: "West Africa Time", value: "GMT +01:00" },
    { name: "Eastern European Time", value: "GMT +02:00" },
    { name: "Central Africa Time", value: "GMT +02:00" },
    { name: "Eastern African Time", value: "GMT +03:00" },
    { name: "Arabian Standard Time", value: "GMT +03:00" },
    { name: "Iran Standard Time", value: "GMT +03:30" },
    { name: "Moscow Standard Time", value: "GMT +03:00" },
    { name: "Gulf Standard Time", value: "GMT +04:00" },
    { name: "Pakistan Standard Time", value: "GMT +05:00" },
    { name: "Indian Standard Time", value: "GMT +05:30" },
    { name: "Nepal Time", value: "GMT +05:45" },
    { name: "Bangladesh Standard Time", value: "GMT +06:00" },
    { name: "Myanmar Time", value: "GMT +06:30" },
    { name: "Indochina Time", value: "GMT +07:00" },
    { name: "China Standard Time", value: "GMT +08:00" },
    { name: "Japan Standard Time", value: "GMT +09:00" },
    { name: "Korean Standard Time", value: "GMT +09:00" },
    { name: "Australian Western Standard Time", value: "GMT +08:00" },
    { name: "Australian Central Standard Time", value: "GMT +09:30" },
    { name: "Australian Eastern Standard Time", value: "GMT +10:00" },
    { name: "Chamorro Standard Time", value: "GMT +10:00" },
    { name: "New Zealand Standard Time", value: "GMT +12:00" },
    { name: "Fiji Time", value: "GMT +12:00" },
    { name: "Tonga Time", value: "GMT +13:00" },
    { name: "Line Islands Time", value: "GMT +14:00" }
];

